name: $(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.rr)

pr:
  - master

trigger:
  batch: true
  branches:
    include:
    - master

resources:
  repositories:
    - repository: MicrosoftIISCommon
      type: github
      name: Microsoft/IIS.Common
      endpoint: GitHub-IIS-Token

jobs:
- template: .azure\templates\build.yml@MicrosoftIISCommon
  parameters:
    agentPoolName: 'VSEngSS-MicroBuild2019-1ES'
    solution: '**\Compression.sln'
    restoreSolution: 'Compression.sln;IIS-Setup/IIS-Setup.sln'
    productMajor: 1
    productMinor: 0
    signType: 'test'
    publishArtifactInstallers: 'true'
    msbuildArgs: '/p:RunWixToolsOutOfProc=true'